#!/usr/bin/env python3

"""
WRF namelist creator
"""

#################################################
#
# requirements
#
#################################################

import os, shutil, sys, glob, stat, filecmp
from datetime import datetime, timedelta
from netCDF4 import Dataset
import subprocess
import pdb
import re

# read the environment variable CIMEROOT in order to set paths to other libraries
CIMEROOT = os.environ.get("CIMEROOT")
if CIMEROOT is None:
    raise SystemExit("ERROR: must set CIMEROOT environment variable")
sys.path.append(os.path.join(CIMEROOT, "scripts", "Tools"))

# other requirements
from standard_script_setup import *
from CIME.case import Case
from CIME.utils import expect
from CIME.buildnml import create_namelist_infile, parse_input
from CIME.utils import run_cmd


#################################################
#
# UnsupportedFeatureException
#
#################################################

class UnsupportedFeatureException(Exception):
    def __init__(self, message="This feature has not been implemented yet!"):
        self.message = message
        super().__init__(self.message)

        
#################################################
#
# dict_to_namelist
#
#################################################

def dict_to_namelist(d):
    namelist_str = ""

    for group_name, group_data in d.items():
        namelist_str += f"&{group_name}\n"
        for key, value in group_data.items():
            namelist_str += f"  {key} = {value}\n"
        namelist_str += "/\n"

    return namelist_str


#################################################
#
# namelist_to_dict
#
#################################################

def namelist_to_dict(namelist_str):

    namelist_data = {}
    current_group = None

    # Remove comments and leading/trailing whitespaces
    namelist_str = re.sub(r"!.*", "", namelist_str).strip()

    # Split the namelist into groups
    groups = namelist_str.split("/")

    for group in groups:
        # Skip empty groups
        if not group.strip():
            continue

        # Extract the group name
        group_name_match = re.match(r"^\s*&(\w+)\s*", group)
        if group_name_match:
            current_group = group_name_match.group(1)
            namelist_data[current_group] = {}
        else:
            raise ValueError("Invalid group name in namelist: " + group)

        # Parse key-value pairs within the group
        key_value_matches = re.findall(r"(\w+)\s*=\s*([^/\n]+)", group)
        for key, value in key_value_matches:
            value = value.strip()
            try:
                # Try converting the value to an int or float
                value = int(value)
            except ValueError:
                try:
                    value = float(value)
                except ValueError:
                    # If the value is a string, remove leading/trailing quotes
                    value = value.strip("'\"")
            namelist_data[current_group][key] = value

    return namelist_data


#################################################
#
# merge dictionaries
#
#################################################

def mergeDicts(d1, d2):

    # create a copy of d1
    d3 = d1
    
    # iterate on the first level of d2 and check if its keys are already in d2
    for k in d2.keys():
        
        if not k in d3.keys():
            
            # in this branch of the if, we know that the key read from d2
            # is not already included in d1, so we can copy the whole element
            d3[k] = d2[k]

        else:

            # in this other branch, we have to iterate over all the elements
            # of d2 and add them manually to d1
            for kk in d2[k].keys():
                d3[k][kk] = d2[k][kk]

    # return the newly created dictionary
    return d3


#################################################
#
# configuration of the logger
#
#################################################

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


#################################################
#
# buildnml
#
#################################################

def buildnml(case, caseroot, compname):

    # debug print
    logger.info("[buildnml][buildnml] === buildnml starting...")

    #################################################
    #
    # read case information
    #
    #################################################

    cimeroot = case.get_value("CIMEROOT")
    srcroot = case.get_value("SRCROOT")
    din_loc_root = case.get_value("DIN_LOC_ROOT")
    atm_grid = case.get_value("ATM_GRID")
    rundir = case.get_value("RUNDIR")

    
    #################################################
    #
    # initialise the dict_namelist
    #
    #################################################
    
    dict_nml = {
        "time_control": {},
        "domains": {},
        "physics": {},
        "noha_mp": {},
        "fdda": {},
        "dynamics": {},
        "bdy_control": {},
        "grib2": {},
        "namelist_quilt": {}
    }
    
    #################################################
    #
    # time_control section
    #
    #################################################
    
    # get options from CIME configuration
    stop_option = case.get_value("STOP_OPTION")
    stop_date = case.get_value("STOP_DATE")    
    stop_n = case.get_value("STOP_N")    
    run_startdate = case.get_value("RUN_STARTDATE")

    # start datetime of the simulation
    start_year, start_month, start_day = map(int, run_startdate.split("-"))
    dict_nml["time_control"]["start_year"] = start_year
    dict_nml["time_control"]["start_month"] = start_month
    dict_nml["time_control"]["start_day"] = start_day
    dict_nml["time_control"]["start_hour"] = "00"
    dict_nml["time_control"]["start_minute"] = "00"
    dict_nml["time_control"]["start_second"] = "00"
    
    # check if the limit is expressed in days or hours
    if stop_option == "ndays":
        days = stop_n
        hours = 0
    elif stop_option == "nhours": 
        days = 0       
        hours = stop_n
    else:
        logging.error("[buildnml][buildnml] === %s yet to develop..." % stop_option)
        raise UnsupportedFeatureException("stop_option=%s yet to develop in LIMES..." % stop_option)
    minutes = 0
    seconds = 0        

    # determine start and end date, time interval
    start_date = datetime(start_year, start_month, start_day, 0, 0, 0)
    time_interval = timedelta(days=days, hours=hours, minutes=minutes)
    end_date = (start_date + time_interval).strftime("%Y-%m-%d")    
    end_year, end_month, end_day = end_date.split("-")
    
    # set run duration
    dict_nml["time_control"]["run_days"] = days
    dict_nml["time_control"]["run_hours"] = hours
    dict_nml["time_control"]["run_minutes"] = minutes
    dict_nml["time_control"]["run_seconds"] = seconds
    dict_nml["time_control"]["end_year"] = end_year
    dict_nml["time_control"]["end_month"] = end_month
    dict_nml["time_control"]["end_day"] = end_day
    dict_nml["time_control"]["end_hour"] = "00"
    dict_nml["time_control"]["end_minute"] = "00"
    dict_nml["time_control"]["end_second"] = "00"
    dict_nml["time_control"]["interval_seconds"] = 21600   
    dict_nml["time_control"]["input_from_file"] = ".true."
    dict_nml["time_control"]["history_interval"] = 360
    dict_nml["time_control"]["io_form_history"] = 2
    dict_nml["time_control"]["io_form_restart"] = 2
    dict_nml["time_control"]["io_form_input"] = 2
    dict_nml["time_control"]["io_form_boundary"] = 2
    dict_nml["time_control"]["io_form_auxinput2"] = 2
    dict_nml["time_control"]["io_form_auxhist3"] = 2
    dict_nml["time_control"]["io_form_auxinput4"] = 2
    dict_nml["time_control"]["history_outname"] = "%s/wrfout_d<domain>_<date>" % (rundir)
    dict_nml["time_control"]["frames_per_outfile"] = 4
    dict_nml["time_control"]["auxhist3_outname"] = "%s/wrfxtrm_d<domain>_<date>" % (rundir)
    dict_nml["time_control"]["auxhist3_interval"] = 1440
    dict_nml["time_control"]["frames_per_auxhist3"] = 1
    dict_nml["time_control"]["restart"] = ".true."
    dict_nml["time_control"]["restart_interval"] = 43200
    dict_nml["time_control"]["write_hist_at_0h_rst"] = ".true."
    dict_nml["time_control"]["output_diagnostics"] = 1      
    dict_nml["time_control"]["auxinput4_inname"] = "%s/wrflowinp_d<domain>" % (rundir)
    dict_nml["time_control"]["auxinput4_interval"] = 360

    #################################################
    #
    # domains section
    #
    #################################################

    dict_nml["domains"]["time_step"] = 24
    dict_nml["domains"]["time_step_fract_num"] = 0
    dict_nml["domains"]["time_step_fract_den"] = 1
    dict_nml["domains"]["max_dom"] = 1
    dict_nml["domains"]["e_we"] = 289
    dict_nml["domains"]["e_sn"] = 403
    dict_nml["domains"]["e_vert"] = 60
    dict_nml["domains"]["p_top_requested"] = 5000
    dict_nml["domains"]["num_metgrid_levels"] = 26
    dict_nml["domains"]["num_metgrid_soil_levels"] = 4
    dict_nml["domains"]["dx"] = 6000
    dict_nml["domains"]["dy"] = 6000
    dict_nml["domains"]["grid_id"] = 1
    dict_nml["domains"]["parent_id"] = 0
    dict_nml["domains"]["i_parent_start"] = 1
    dict_nml["domains"]["j_parent_start"] = 1
    dict_nml["domains"]["parent_grid_ratio"] = 1
    dict_nml["domains"]["parent_time_step_ratio"] = 1
    dict_nml["domains"]["feedback"] = 1
    dict_nml["domains"]["smooth_option"] = 0
    dict_nml["domains"]["eta_levels"] = [
        1.000, 0.9973, 0.9947, 0.9921, 0.9895,
        0.9869, 0.9843, 0.9816, 0.979, 0.97645,
        0.9739, 0.9687, 0.9635, 0.956, 0.9485,
        0.9389, 0.9294, 0.9182, 0.907, 0.8944,
        0.8818, 0.8543, 0.825, 0.7945, 0.763,
        0.7311, 0.699, 0.6669, 0.6352, 0.604,
        0.5735, 0.5437, 0.5148, 0.4869, 0.4599,
        0.4339, 0.4089, 0.3848, 0.3617, 0.3394,
        0.3179, 0.2972, 0.2772, 0.2578, 0.239,
        0.2207, 0.2028, 0.1854, 0.1682, 0.1514,
        0.1323, 0.1159, 0.0999, 0.0843, 0.069,
        0.0542, 0.0397, 0.0257, 0.0122, 0.000
    ]
    
    #################################################
    #
    # physics section
    #
    #################################################

    dict_nml["physics"]["physics_suite"] = 'CONUS'
    dict_nml["physics"]["mp_physics"] = 8
    dict_nml["physics"]["cu_physics"] = 1
    dict_nml["physics"]["ra_lw_physics"] = 4
    dict_nml["physics"]["ra_sw_physics"] = 4
    dict_nml["physics"]["cam_abs_freq_s"] = 21600
    dict_nml["physics"]["levsiz"] = 59
    dict_nml["physics"]["paerlev"] = 29
    dict_nml["physics"]["cam_abs_dim1"] = 4
    dict_nml["physics"]["cam_abs_dim2"] = 38
    dict_nml["physics"]["o3input"] = 2
    dict_nml["physics"]["aer_opt"] = 1
    dict_nml["physics"]["alevsiz"] = 12
    dict_nml["physics"]["no_src_types"] = 6
    dict_nml["physics"]["bl_pbl_physics"] = 1
    dict_nml["physics"]["sf_sfclay_physics"] = 11
    dict_nml["physics"]["sf_surface_physics"] = 2
    dict_nml["physics"]["radt"] = 10
    dict_nml["physics"]["bldt"] = 0
    dict_nml["physics"]["cudt"] = 5
    dict_nml["physics"]["isfflx"] = 1
    dict_nml["physics"]["ifsnow"] = 1
    dict_nml["physics"]["icloud"] = 1
    dict_nml["physics"]["surface_input_source"] = 1
    dict_nml["physics"]["num_soil_layers"] = 4
    dict_nml["physics"]["num_land_cat"] = 24
    dict_nml["physics"]["sf_urban_physics"] = 0
    dict_nml["physics"]["sst_update"] = 1

    #################################################
    #
    # dynamics section
    #
    ###############################################    

    dict_nml["dynamics"]["w_damping"] = 0
    dict_nml["dynamics"]["diff_opt"] = 1
    dict_nml["dynamics"]["km_opt"] = 4
    dict_nml["dynamics"]["diff_6th_opt"] = 2
    dict_nml["dynamics"]["diff_6th_factor"] = 0.12
    dict_nml["dynamics"]["base_temp"] = 290.
    dict_nml["dynamics"]["damp_opt"] = 0
    dict_nml["dynamics"]["zdamp"] = 5000.
    dict_nml["dynamics"]["dampcoef"] = 0.2
    dict_nml["dynamics"]["khdif"] = 0
    dict_nml["dynamics"]["kvdif"] = 0
    dict_nml["dynamics"]["non_hydrostatic"] = True
    dict_nml["dynamics"]["moist_adv_opt"] = 1
    dict_nml["dynamics"]["scalar_adv_opt"] = 1

    #################################################
    #
    # bdy_control section
    #
    ###############################################    

    dict_nml["bdy_control"]["spec_bdy_width"] = 5
    dict_nml["bdy_control"]["spec_zone"] = 1
    dict_nml["bdy_control"]["relax_zone"] = 4
    dict_nml["bdy_control"]["specified"] = True
    dict_nml["bdy_control"]["nested"] = False

    #################################################
    #
    # namelist_quilt section
    #
    ###############################################    

    dict_nml["namelist_quilt"]["nio_tasks_per_group"] = 0
    dict_nml["namelist_quilt"]["nio_groups"] = 1
    
    #################################################
    #
    # merge users' custom namelist
    #
    #################################################
    
    # read the namelist with local users' preferences
    user_nml_file = "%s/user_nl_wrf" % (caseroot)
    with open(user_nml_file, "r") as f:
        user_nml_str = f.read()
    user_dict_nml = namelist_to_dict(user_nml_str)

    # merging the global and the user dict_namelists, then convert it to namelist
    final_dict_nml = mergeDicts(dict_nml, user_dict_nml)
    final_nml = dict_to_namelist(final_dict_nml)

    #################################################
    #
    # write to file
    #
    #################################################
    
    # output the namelist to file
    nml_file = "%s/namelist.input" % (rundir)
    logging.info("[buildlib][_main_func] === Writing namelist to %s" % nml_file)
    with open(nml_file, "w") as f:
        f.write(final_nml)
    
    
#################################################
#
# _main_func
#
#################################################
    
def _main_func(args):

    # debug information
    logging.info("[buildlib][_main_func] === Method _main_func starting...")

    # parse input
    caseroot, libroot, bldroot = parse_input(sys.argv)

    # invoke buildnml
    logging.info("[buildlib][_main_func] === Invoking buildnml...")
    buildnml(case, caseroot, "wrf")
    
    
#################################################
#
# main
#
#################################################

if __name__ == "__main__":

    # invoke the buildml function
    logger.info("[buildnml][__main__] === Invoking _main_func...")
    _main_func(sys.argv)


